name: docker_builds

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-push-linux-image:
    name: Linux (Ubuntu)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/ubuntu
          push: true
          tags: ghcr.io/nonameentername/godot-ubuntu:${{ env.VERSION }},ghcr.io/nonameentername/godot-ubuntu:latest

  build-and-push-windows-image:
    name: Windows (MinGW)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/mingw
          push: true
          tags: ghcr.io/nonameentername/godot-mingw:${{ env.VERSION }},ghcr.io/nonameentername/godot-mingw:latest

  build-and-push-macos-image:
    name: MacOS (osxcross)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/osxcross
          push: true
          tags: ghcr.io/nonameentername/godot-osxcross:${{ env.VERSION }},ghcr.io/nonameentername/godot-osxcross:latest

  build-and-push-ios-image:
    name: iOS (ioscross)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/ioscross
          push: true
          tags: ghcr.io/nonameentername/godot-ioscross:${{ env.VERSION }},ghcr.io/nonameentername/godot-ioscross:latest
          build-args: |
            DOWNLOAD_URL=${{ vars.IOSCROSS_DOWNLOAD_URL }}
          secrets: |
            IOSCROSS_PASSWORD=${{ secrets.IOSCROSS_PASSWORD }}

  build-and-push-android-image:
    name: Android
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/android
          push: true
          tags: ghcr.io/nonameentername/godot-android:${{ env.VERSION }},ghcr.io/nonameentername/godot-android:latest

  build-and-push-wasm-image:
    name: Wasm (emscripten)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/web
          push: true
          tags: ghcr.io/nonameentername/godot-wasm:${{ env.VERSION }},ghcr.io/nonameentername/godot-wasm:latest
